drop table if exists AnswerOptions cascade;
drop table if exists QuestionsForLessons cascade;
drop table if exists Questions cascade;
drop table if exists LessonsForCourses cascade;
drop table if exists Lessons cascade;
drop table if exists Courses cascade;
drop table if exists Users cascade;


create table Users
(
    user_id            int          not null generated by default as identity primary key,
    user_login         varchar(127) not null unique,
    user_password_hash varchar(64) not null
);


create table Courses
(
    course_id          int          not null generated by default as identity primary key,
    course_name        varchar(127) not null,
    course_description text         not null
);


create table Lessons
(
    lesson_id   int          not null generated by default as identity primary key,
    lesson_name varchar(127) not null
);

create table LessonsForCourses
(
    course_id int not null references Courses (course_id),
    lesson_id int not null references Lessons (lesson_id),
    lesson_number int not null,
    primary key (course_id, lesson_id),
    unique (course_id, lesson_number)
);


create table Questions
(
    question_id              int  not null generated by default as identity primary key,
    question_text            text not null,
    correct_answer_option_id int  not null
);

create table QuestionsForLessons
(
    lesson_id   int not null references Lessons (lesson_id),
    question_id int not null references Questions (question_id),
    question_number int not null,
    primary key (lesson_id, question_id),
    unique (lesson_id, question_number)
);

create table AnswerOptions
(
    answer_option_id   int  not null generated by default as identity primary key,
    question_id        int  not null references Questions (question_id),
    answer_option_text text not null
);

alter table Questions add constraint correct_answer_fk foreign key (correct_answer_option_id) references AnswerOptions (answer_option_id) deferrable initially immediate;