name: Client test

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '15.0.1'
               
      - name: Install dependencies
        run: yarn install
        working-directory: ./client
        
      - name: Run unit and component tests
        run: yarn test:unit
        working-directory: ./client
        
      - name: Build containers
        run: docker-compose build
        
      - name: Start containers
        run: docker-compose up -d
        
      - name: Run e2e test
        run: HOST=http://localhost:7001 yarn test:e2e
        working-directory: ./client
        
      - name: Stop containers
        run: docker-compose down
      
