name: Server test

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
      - name: Add checkout action 
        uses: actions/checkout@v2
      
      - name: Download chrome browser
        run: sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                
      - name: Build chrome browser 
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '11'
          distribution: adopt
          
      - name: Build and test
        working-directory: ./server
        run: sudo ./gradlew build
