name: Server test

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
      - name: Add checkout action 
        uses: actions/checkout@v2
      
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '11'
          distribution: adopt
          
      - name: Build containers
        run: docker-compose build
        
      - name: Start containers
        run: docker-compose up -d 
          
      - name: Build and test
        working-directory: ./server
        run: sudo ./gradlew build
        
      - name: Stop containers
        run: docker-compose down
